//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realtime_graph.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class IE_COMMONEntities : DbContext
    {
        public IE_COMMONEntities()
            : base("name=IE_COMMONEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SF_BoothVote> SF_BoothVote { get; set; }
    
        public virtual ObjectResult<sp_sum_boot_vote_Result> sp_sum_boot_vote()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sum_boot_vote_Result>("sp_sum_boot_vote");
        }
    }
}
