//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Realtime_graph.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SF_BoothVote
    {
        public string EmpID { get; set; }
        public string Vote { get; set; }
    }
}
